name: Deploy-Github-Pages

on:
  push:
    branches: [main]

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - uses: actions/cache@v3
        with:
          path: '.jampack'
          key: jampack-${{ github.run_id }}
          restore-keys: |
            jampack

      # run build script
      - name: Build project via vite
        run: yarn build

      - name: Build project via jampack
        run: |
          npm i -g @divriots/jampack
          jampack ./build

      # remove useless .md files
      - name: Removing markdown files
        run: |
          find . -type f -iname \*.md -delete
          ls -Rl ./build

      # please check out the docs of the workflow for more details
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          # deploy to gh-pages branch
          target_branch: gh-pages
          # deploy the default output dir of SvelteKit
          build_dir: build
          jekyll: false
        env:
          # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
